# Generated by Django 5.2.17 on 2026-10-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0003_color_sin_canto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='La que usa el código (por ejemplo "zicar"). No se cambia.', max_length=40, unique=True, verbose_name='clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TallerModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prendido', models.BooleanField(default=True, verbose_name='prendido')),
                ('configuracion', models.JSONField(blank=True, default=dict, verbose_name='configuración')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='modulos.modulo', verbose_name='módulo')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'módulo del taller',
                'verbose_name_plural': 'módulos del taller',
                'ordering': ['modulo__nombre'],
                'constraints': [models.UniqueConstraint(fields=('taller', 'modulo'), name='un_modulo_por_taller')],
            },
        ),
    ]
