# Generated by Django 5.2.17 on 2026-10-05 20:06

import django.db.models.deletion
import proyectos.archivos
import proyectos.models
import talleres.archivos
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo_cliente', models.CharField(default=proyectos.models.codigo_nuevo, editable=False, max_length=32, unique=True, verbose_name='código del cliente')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='número')),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('convirtiendo', 'Convirtiendo'), ('listo', 'Listo'), ('error', 'Error')], default='en_cola', max_length=12, verbose_name='estado')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('avisos', models.JSONField(blank=True, default=list, verbose_name='avisos')),
                ('resumen', models.JSONField(blank=True, default=dict, verbose_name='resumen')),
                ('faltan_texturas', models.JSONField(blank=True, default=list, verbose_name='materiales sin textura')),
                ('archivo_proyecto', models.CharField(blank=True, max_length=400, verbose_name='JSON del proyecto')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('empezada', models.DateTimeField(blank=True, null=True, verbose_name='empezada')),
                ('terminada', models.DateTimeField(blank=True, null=True, verbose_name='terminada')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='proyectos.proyecto')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'versión',
                'verbose_name_plural': 'versiones',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='version_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='proyectos.version', verbose_name='versión actual'),
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dxf', 'DXF 3D'), ('ocp', 'Lista de OptiCut')], max_length=3, verbose_name='tipo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('archivo', models.FileField(max_length=400, upload_to=proyectos.archivos.ruta_original, verbose_name='archivo')),
                ('tamano', models.PositiveBigIntegerField(default=0, verbose_name='tamaño')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originales', to='proyectos.version')),
            ],
            options={
                'verbose_name': 'archivo original',
                'verbose_name_plural': 'archivos originales',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('clave', models.CharField(editable=False, max_length=200)),
                ('ruta_polyboard', models.CharField(blank=True, max_length=300, verbose_name='imagen en Polyboard')),
                ('ancho_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='ancho que cubre la imagen (mm)')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('textura', models.ImageField(blank=True, max_length=300, upload_to=talleres.archivos.ruta_de_taller, verbose_name='textura')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('taller', 'clave'), name='un_material_por_nombre')],
            },
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('proyecto', 'numero'), name='un_numero_por_proyecto'),
        ),
    ]
