# Generated by Django 5.2.17 on 2026-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'material', 'verbose_name_plural': 'materiales'},
        ),
        migrations.RemoveConstraint(
            model_name='material',
            name='un_material_por_nombre',
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('tablero', 'Tablero'), ('canto', 'Canto')], default='tablero', editable=False, max_length=7, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('taller', 'tipo', 'clave'), name='un_material_por_tipo_y_nombre'),
        ),
    ]
