# Generated by Django 5.2.17 on 2026-10-06 23:38

import django.db.models.deletion
import proyectos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_faltan_texturas_con_tipo'),
        ('talleres', '0002_marca_y_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=proyectos.models.codigo_de_link, editable=False, max_length=32, unique=True, verbose_name='código')),
                ('vence', models.DateTimeField(blank=True, null=True, verbose_name='vence')),
                ('anulado', models.DateTimeField(blank=True, null=True, verbose_name='anulado')),
                ('visitas', models.PositiveIntegerField(default=0, verbose_name='visitas')),
                ('ultima_visita', models.DateTimeField(blank=True, null=True, verbose_name='última visita')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='proyectos.proyecto')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'link del cliente',
                'verbose_name_plural': 'links del cliente',
                'ordering': ['-creado'],
            },
        ),
    ]
