# Generated by Django 5.2.17 on 2026-10-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_marca_y_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='tipo',
            field=models.CharField(choices=[('dxf', 'DXF 3D'), ('ocp', 'Lista de OptiCut'), ('zip', 'Carpeta del postprocesador')], max_length=3, verbose_name='tipo'),
        ),
    ]
