# Generated by Django 5.2.17 on 2026-10-05 17:53

import django.db.models.deletion
import talleres.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='Va en la dirección del taller: app.dominio/esta-direccion/. Minúsculas y guiones.', max_length=40, unique=True, validators=[talleres.models.validar_slug_de_taller], verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='mail')),
                ('rol', models.CharField(choices=[('dueno', 'Dueño'), ('oficina', 'Oficina'), ('armador', 'Armador'), ('instalador', 'Instalador')], max_length=12, verbose_name='rol')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('vence', models.DateTimeField(verbose_name='vence')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('usada', models.DateTimeField(blank=True, null=True, verbose_name='usada')),
                ('invitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('dueno', 'Dueño'), ('oficina', 'Oficina'), ('armador', 'Armador'), ('instalador', 'Instalador')], max_length=12, verbose_name='rol')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('pin', models.CharField(blank=True, max_length=128, verbose_name='PIN (cifrado)')),
                ('pin_fallos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos fallidos de PIN')),
                ('pin_bloqueado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='PIN bloqueado hasta')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
                'ordering': ['usuario__nombre', 'usuario__email'],
                'constraints': [models.UniqueConstraint(fields=('taller', 'usuario'), name='una_membresia_por_taller')],
            },
        ),
    ]
