# Generated by Django 5.2.17 on 2026-10-06 23:38

import django.core.validators
import talleres.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'El color tiene que ser como #1D5FE0.')], verbose_name='color'),
        ),
        migrations.AddField(
            model_name='taller',
            name='logo',
            field=models.ImageField(blank=True, max_length=300, upload_to=talleres.archivos.ruta_de_logo, verbose_name='logo'),
        ),
    ]
