# Generated by Django 5.2.17 on 2026-10-07 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_marca_y_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='color_sin_canto',
            field=models.CharField(default='#B58F63', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'El color tiene que ser como #B58F63.')], verbose_name='color de los lados sin canto'),
        ),
    ]
