# Generated by Django 5.2.17 on 2026-10-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0005_alter_original_tipo'),
        ('talleres', '0003_color_sin_canto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoZicar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('convirtiendo', 'Convirtiendo'), ('listo', 'Listo'), ('error', 'Error')], default='en_cola', max_length=12, verbose_name='estado')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('avisos', models.JSONField(blank=True, default=list, verbose_name='para revisar a mano')),
                ('piezas', models.PositiveIntegerField(default=0, verbose_name='piezas convertidas')),
                ('archivo', models.CharField(blank=True, max_length=400, verbose_name='ZIP')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='nombre del ZIP')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('empezado', models.DateTimeField(blank=True, null=True, verbose_name='empezado')),
                ('terminado', models.DateTimeField(blank=True, null=True, verbose_name='terminado')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zicar', to='proyectos.version')),
            ],
            options={
                'verbose_name': 'resultado Zicar',
                'verbose_name_plural': 'resultados Zicar',
            },
        ),
    ]
