# Generated by Django 5.2.17 on 2026-10-07 00:41

import django.db.models.deletion
import talleres.archivos
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_marca_y_link'),
        ('talleres', '0003_color_sin_canto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=4000, verbose_name='qué hay que hacer')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en proceso', 'En proceso'), ('hecho', 'Hecho'), ('instalado', 'Instalado')], default='pendiente', max_length=12, verbose_name='estado')),
                ('piezas', models.JSONField(blank=True, default=list, verbose_name='piezas')),
                ('muebles', models.JSONField(blank=True, default=list, verbose_name='muebles')),
                ('limite', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='anotado')),
                ('iniciado_en', models.DateTimeField(blank=True, null=True, verbose_name='empezado')),
                ('hecho_en', models.DateTimeField(blank=True, null=True, verbose_name='hecho')),
                ('instalado_en', models.DateTimeField(blank=True, null=True, verbose_name='instalado')),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='para quién')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='anotado por')),
                ('hecho_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='empezado por')),
                ('instalado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='instalado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='proyectos.proyecto')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'trabajo',
                'verbose_name_plural': 'trabajos',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(max_length=300, upload_to=talleres.archivos.ruta_de_taller, verbose_name='archivo')),
                ('tamano', models.PositiveIntegerField(default=0, verbose_name='tamaño')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='subida')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='trabajos.trabajo')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CambioDeEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(choices=[('pendiente', 'Pendiente'), ('en proceso', 'En proceso'), ('hecho', 'Hecho'), ('instalado', 'Instalado')], max_length=12, verbose_name='de')),
                ('a', models.CharField(choices=[('pendiente', 'Pendiente'), ('en proceso', 'En proceso'), ('hecho', 'Hecho'), ('instalado', 'Instalado')], max_length=12, verbose_name='a')),
                ('cuando', models.DateTimeField(verbose_name='cuándo')),
                ('taller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='talleres.taller')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='quién')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='trabajos.trabajo')),
            ],
            options={
                'verbose_name': 'cambio de estado',
                'verbose_name_plural': 'cambios de estado',
                'ordering': ['cuando', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['taller', 'proyecto'], name='trabajos_tr_taller__d91348_idx'),
        ),
    ]
